.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH T10-KEYBOARD 1 "December 04, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
.B t10-keyboard 
\- An intelligent on-screen keyboard with word completition.
.SH SYNOPSIS
.B t10-keyboard
 [-v]
.SH DESCRIPTION
This manual page documents briefly the
.B t10-keyboard
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBt10-keyboard\fP is a program that provides an on-screen keyboard, based on Java and thus mostly system independent, that has a intelligent auto-complete function for fast typing. It can be loaded with personal texts, to optimize the auto-complete function.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-v, \-\-version
Show version of program.
.br
.SH AUTHOR
t10-keyboard was written by FIT 42 <fit-42@googlegroups.com>.
.PP
This manual page was written by Nicolai Ommer <nicolai.ommer@gmail.com>.
